#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

$envExists = file_exists(__DIR__ . '/env.php');

if ($envExists)
{
    require(__DIR__ . '/env.php');
}

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');
require(__DIR__ . '/common/config/bootstrap.php');
require(__DIR__ . '/console/config/bootstrap.php');

if ($envExists && ENV_CONFIG === 'dev')
{
    $config = yii\helpers\ArrayHelper::merge(
        require(__DIR__ . '/common/config/main-local.php'),
        require(__DIR__ . '/console/config/main-local.php')
    );
} else {
    $config = yii\helpers\ArrayHelper::merge(
        require(__DIR__ . '/common/config/main.php'),
        require(__DIR__ . '/console/config/main.php')
    );
}

//向容器注册接口
require(__DIR__ . '/yii-reg.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
