<?php
/**
 * Created by PhpStorm.
 * User: mac
 * Date: 16/12/12
 * Time: 上午9:27
 */
namespace app\controllers;

use common\services\ErrorService;
use common\services\LogService;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;

class BaseController extends Controller
{

    protected $logid = '0';
    
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * 加载错误action
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        $method = $action->actionMethod;
        //var_dump($method);
        $param = array(
            'actionSendWechat',
            'actionAddMessage',
        );
        if (!in_array($method, $param) && Yii::$app->request->isPost) {
            $this->logid = LogService::inputLog(Yii::$app->request);
        }
        if (Yii::$app->user->identity) {
            $auth_key = Yii::$app->user->identity->auth_key;
            $session_auth_key = Yii::$app->session->get('auth_key');
            if (!$session_auth_key || $auth_key!= $session_auth_key) {
                Yii::$app->user->logout();
                Yii::$app->response->headers->set('Header-Error', 50001);
            }
        } else {
            Yii::$app->response->headers->set('Header-Error', 50001);
        }
        return parent::beforeAction($action);
    }

    public function afterAction($action, $result)
    {
        if (!empty($this->logid)) {
            LogService::outputLog($this->logid, $result);
        }

        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     * @created by Jhu
     * 错误logs处理
     */
    public function actionErrorMonitor()
    {
        $exception = Yii::$app->errorHandler->exception;
        if ($exception instanceof \yii\web\HttpException) {
            $code = $exception->statusCode;
        } else {
            $code = $exception->getCode();
        }

        //404的错误不保存
        if ($code != 404) {
            ErrorService::addChannelError($exception, Yii::$app->request);
        }
    }
}
