<?php

namespace console\controllers;

use Yii;
use yii\console\Controller;
use common\widgets\Queue;
use common\widgets\TemplateBuilder;
use console\models\cost\SalesPushMessage;
use console\models\record\SalesChannel;

/**
 * Channel controller
 */
class ArticleController extends Controller
{

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }

    /*
     * 推送软文
     * create by sjy 2017-05-19
     */
    public function actionPushArticle()
    {
        //查询未推送的消息
        $data = SalesPushMessage::find()
            ->select('id, title, content, params, type, con_time, con_income,user_new,user_have_value,user_no_value')
            ->where('uid=0 and is_send=0 and type = 3 ')
            ->asArray()
            ->all();

        $messageList = [];
        for ($i = 0; $i < count($data); $i++) {
            //更新发送记录
            $sql = 'UPDATE sales_push_message SET is_send = 1 WHERE id = :id';
            Yii::$app->db->createCommand($sql)
                ->bindValue(':id', $data[$i]["id"])
                ->execute();
            $people = '';
            if (!empty($data[$i]["user_new"])) {
                $people .= '1,';
            }
            if (!empty($data[$i]["user_have_value"])) {
                $people .= '2,';
            }
            if (!empty($data[$i]["user_no_value"])) {
                $people .= '3,';
            }
            $people = substr($people, 0, strlen($people) - 1);
            //获取发送消息模板的用户openid
            $sendUser = SalesChannel::find()
                ->select('bind_openid,id')
                ->where("status = 1 and message_type in (" . $people . ")")
                ->asArray()
                ->all();
            if (!empty($sendUser)) {
                for ($j = 0; $j < count($sendUser); $j++) {
                    //定义消息消息模板
                    $param = array(
                        'template_id' => Yii::$app->params['channel_template_todo'],
                        'firstValue' => '今日红包奖励软文已准备好，点击进入分享后获取现金红包，最高88元哟。',
                        'key1word' => $data[$i]['title'],
                        'key2word' => [
                            'value' => $data[$i]['content'],
                            'color' => '#c9302c'
                        ],
                        'key3word' => date('Y年m月d日', time()),
                        'remark' => '点击查看详情',
                        'url' => Yii::$app->params['channel_base_url'] . "article/share?id=" . $data[$i]['params'] . '_' . $sendUser[$j]['id'],
                        'keyword_num' => 3
                    );
                    //将要发送的消息模板放到消息数组中
                    $messageList[] = TemplateBuilder::build($param, (string)$sendUser[$j]["bind_openid"]);
                }
            }
        }

        if (!empty($messageList)) {
            //将要发送的内容发送到队列中
            Queue::batchProduce($messageList, 'template', 'channel_template');
        }
    }
}
